# Site description
name: Ross Anderson
description: canadian software engineer
meta_description: "Ross Anderson, software engineer"
cover: "images/sombrilla-screenshot.png"

# Collections
collections:
  projects:
    output: true

# Excerpts
excerpt_separator: "---"

# Markdown rendering
markdown: kramdown
highlighter: pygments

logo: false
paginate: 15
paginate_path: blog/page:num
baseurl: /
domain_name: 'http://rossanderson.ca'

# Details for the RSS feed generator
url:            'rossanderson.ca'
author:         'Ross Anderson'
