name: Ross Anderson
description: Canadian software developer
meta_description: "Ross Anderson - Canadian software developer"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://rossanderson.ca'

# Details for the RSS feed generator
url:            'rossanderson.ca'
author:         'Ross Anderson'
